services:
  - type: worker
    name: telegram-bot-worker
    env: python
    plan: free
    branch: main
    repo: https://github.com/your-username/your-repo-name
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: DATABASE_URL
        value: postgres://user:pass@host:port/dbname
      - key: OPENROUTER_API_KEY
        value: sk-xxxx
      - key: ADMIN_CHAT_ID
        value: 123456789
